// <auto-generated />
namespace AuctionDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class FK3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FK3));
        
        string IMigrationMetadata.Id
        {
            get { return "202005121750479_FK3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
